services:
  - type: web
    name: HybridTrainingClubServer
    runtime: python
    buildCommand: ""  # Leave blank unless you need to specify a build process
    startCommand: uvicorn main:app --host 0.0.0.0 --port 10000